version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=clinica_user
      - POSTGRES_PASSWORD=clinica_password
      - POSTGRES_DB=clinica_db
    ports:
      - "5432:5432"
    networks:
      - clinica-net

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://clinica_user:clinica_password@db:5432/clinica_db
      - CLINICORP_API_KEY=${CLINICORP_API_KEY}
      - CLINICORP_API_URL=${CLINICORP_API_URL}
    depends_on:
      - db
    networks:
      - clinica-net

volumes:
  postgres_data:


networks:
  clinica-net:
    driver: bridge
